import { Movie, Theatre } from '@/types/database';

export const INITIAL_MOVIES: Movie[] = [
  {
    id: 'm1-paradise',
    title: 'Paradise',
    slug: 'paradise',
    poster_url: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=500&q=80',
    language: 'Tamil',
    release_date: '2026-09-24',
    is_active: true,
  },
  {
    id: 'm2-coolie',
    title: 'Coolie',
    slug: 'coolie',
    poster_url: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=500&q=80',
    language: 'Tamil',
    release_date: '2026-10-02',
    is_active: true,
  },
  {
    id: 'm3-thug-life',
    title: 'Thug Life',
    slug: 'thug-life',
    poster_url: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=500&q=80',
    language: 'Tamil',
    release_date: '2026-11-12',
    is_active: true,
  },
  {
    id: 'm4-dragon',
    title: 'Dragon',
    slug: 'dragon',
    poster_url: 'https://images.unsplash.com/photo-1518676590629-3dcbd9c5a5c9?w=500&q=80',
    language: 'Tamil',
    release_date: '2026-09-30',
    is_active: true,
  },
  {
    id: 'm5-secret-wars',
    title: 'Avengers: Secret Wars',
    slug: 'avengers-secret-wars',
    poster_url: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=500&q=80',
    language: 'English',
    release_date: '2027-05-01',
    is_active: true,
  },
];

export const INITIAL_THEATRES: Theatre[] = [
  // Coimbatore
  {
    id: 't1-kg-cinemas-cbe',
    name: 'KG Cinemas (Screen 4K Atmos)',
    city: 'Coimbatore',
    address: 'Race Course Road, Gopalapuram',
    chain: 'KG',
    supported_platforms: ['bookmyshow', 'district', 'both'],
  },
  {
    id: 't2-broadway-cinemas-cbe',
    name: 'Broadway Cinemas (EPIQ Screen)',
    city: 'Coimbatore',
    address: 'Avinashi Road, Peelamedu',
    chain: 'Broadway',
    supported_platforms: ['bookmyshow', 'district', 'both'],
  },
  {
    id: 't3-inox-prozone-cbe',
    name: 'INOX Prozone Mall',
    city: 'Coimbatore',
    address: 'Prozone Mall, Sathy Road',
    chain: 'PVR INOX',
    supported_platforms: ['bookmyshow', 'both'],
  },
  {
    id: 't4-miraj-cinemas-cbe',
    name: 'Miraj Cinemas (Fun Republic Mall)',
    city: 'Coimbatore',
    address: 'Avinashi Road, Peelamedu',
    chain: 'Miraj',
    supported_platforms: ['bookmyshow', 'district', 'both'],
  },
  // Chennai
  {
    id: 't5-pvr-sathyam-chn',
    name: 'PVR Sathyam Cinemas (Royapettah)',
    city: 'Chennai',
    address: 'Thiru Vi Ka Road, Royapettah',
    chain: 'PVR INOX',
    supported_platforms: ['bookmyshow', 'district', 'both'],
  },
  {
    id: 't6-pvr-vr-mall-chn',
    name: 'PVR VR Mall (Anna Nagar)',
    city: 'Chennai',
    address: 'Jawaharlal Nehru Road, Anna Nagar',
    chain: 'PVR INOX',
    supported_platforms: ['bookmyshow', 'district', 'both'],
  },
  {
    id: 't7-vetri-cinemas-chn',
    name: 'Vetri Theatres RGB Laser (Chromepet)',
    city: 'Chennai',
    address: 'GST Road, Chromepet',
    chain: 'Vetri',
    supported_platforms: ['bookmyshow', 'district', 'both'],
  },
  // Bangalore
  {
    id: 't8-pvr-forum-koramangala-blr',
    name: 'PVR Forum Mall (Koramangala)',
    city: 'Bangalore',
    address: 'Hosur Road, Koramangala',
    chain: 'PVR INOX',
    supported_platforms: ['bookmyshow', 'district', 'both'],
  },
  {
    id: 't9-inox-garuda-blr',
    name: 'INOX Garuda Mall (Magrath Road)',
    city: 'Bangalore',
    address: 'Magrath Road, Ashok Nagar',
    chain: 'PVR INOX',
    supported_platforms: ['bookmyshow', 'district', 'both'],
  },
  {
    id: 't10-cinepolis-meenakshi-blr',
    name: 'Cinepolis Royal Meenakshi Mall',
    city: 'Bangalore',
    address: 'Bannerghatta Main Road',
    chain: 'Cinepolis',
    supported_platforms: ['bookmyshow', 'district', 'both'],
  },
  // Hyderabad
  {
    id: 't11-prasads-multiplex-hyd',
    name: 'Prasads Multiplex (Large Screen)',
    city: 'Hyderabad',
    address: 'NTR Gardens, Khairatabad',
    chain: 'Prasads',
    supported_platforms: ['bookmyshow', 'district', 'both'],
  },
  {
    id: 't12-amb-cinemas-hyd',
    name: 'AMB Cinemas (Gachibowli)',
    city: 'Hyderabad',
    address: 'Sarath City Capital Mall, Gachibowli',
    chain: 'AMB',
    supported_platforms: ['bookmyshow', 'district', 'both'],
  },
];
